spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-eureka-client
server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#  關閉自動保護模式
#  server:
#    enable-self-preservation: false
---
spring:
  profiles: test
  application:
    name: microservicecloud-config-eureka-client
server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
